# Generated by Django 4.2.6 on 2023-10-19 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakfastory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakfastory.mealtype')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
